### ISSUE TITLE
Problems identifying the message source

### ISSUE THREAD

**Issue by KodeZ** [paolo-losi/stormed-amqp#26]
Hi

Thanks for a great library. It seems to do close to exactly what I need. I do have an issue though, and it might be just me being thick-headed, but if you could spare the time, I would love your input.

I am running a pub/sub scheme, where I push data to an exchange with different keys. At the same time a bunch of clients will create their own queues and bind to that exchange/key pair. It is a one to many relationship. The clients will access the data using long-poll and tornadoweb.

The problem I am having is that when the callback from the consume arrives, I only get the message as a parameter to the callback. I don't know which queue the message was received from.

I did take some ideas from your benchmark.py example, and there you fill a request_map using the message body text as key. As I don't send the message, I only receive it, all I know at the point when consume is called is the exchage/key and queue name. As every client has an unique queue name, but several might be subscribed to the same exchange/key, I can really only use the queue name as a request_map key. Is it here that I am wrong?

I cannot set anything in the message either, like reply-to, because that will go to several clients, so that will not be unique either.

Is there a way to get hold of the queue name the message is coming from?

**Comment by paolo-losi** [comment]
Hi @KodeZ,

I have a really hard time figuring out what your are trying to accomplish.
Let'me try to guess and give you a suggestion. If this doesn't apply try to share some code on a gist
and I'll be happy to help you.

I guess your problem is due to the fact that you are using the same callback handler for all Channel.consume(). One option that you have is to register a partial function as a callback

```Python
from functools import partial

def consume_callback(queue_name, msg):
    pass

channel.consume(queue_name, partial(consume_callback, queue_name))
```

Let me know if this solve your problem ...

**Comment by KodeZ** [comment]
Excellent! Not that good with python, so that was very good. Thank you!
